apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: busybox-httpserver
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/maartenor/jenkins-sink.git
    targetRevision: HEAD
    path: manifests
  destination:
    server: https://kubernetes.default.svc
    namespace: develop
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
