apiVersion: v1
kind: Service
metadata:
  name: httpserver
  namespace: develop
  labels:
    usage: development
spec:
  selector:
    app: busybox-httpserver
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8088
  type: ClusterIP
