apiVersion: v1
kind: Service
metadata:
  name: busybox-httpserver
  namespace: develop
spec:
  selector:
    app: busybox-httpserver
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8088
  type: ClusterIP
